apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-asr-store-admin-deployment
  labels:
    app: ms-asr-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-asr-store-admin
  template:
    metadata:
      labels:
        app: ms-asr-store-admin
    spec:
      containers:
      - name: ms-asr-store-admin
        image: admin-service:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3005
        env:
        - name: MYSQLUSER
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLUSER
        - name: MYSQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLPASSWORD
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: NODE_ENV
        - name: ADMIN_SERVICE_PORT
          value: "3005"
        - name: MYSQLHOST
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: MYSQLHOST
        - name: MYSQLPORT
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: MYSQLPORT
        - name: USERDATABASE
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: USERDATABASE
        - name: ITEMDATABASE
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: ITEMDATABASE
        - name: CARTDATABASE
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: CARTDATABASE
        - name: ORDERDATABASE
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: ORDERDATABASE
        - name: ITEM_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: ITEM_SERVICE_URL
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: USER_SERVICE_URL
        - name: CART_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: CART_SERVICE_URL
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: ORDER_SERVICE_URL
---
kind: Service
apiVersion: v1
metadata:
  name: ms-asr-store-admin-service
  labels:
    app: ms-asr-store
spec:
  selector:
    app: ms-asr-store-admin
  type: NodePort
  ports:
  - name: user-port
    port: 3005
    targetPort: 3005
    nodePort: 30005