apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-asr-store-cart-deployment
  labels:
    app: ms-asr-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-asr-store-cart
  template:
    metadata:
      labels:
        app: ms-asr-store-cart
    spec:
      containers:
      - name: ms-asr-store-cart
        image: cart-service:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
        env:
        - name: MYSQLUSER
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLUSER
        - name: MYSQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLPASSWORD
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: NODE_ENV
        - name: CART_SERVICE_PORT
          value: "3003"
        - name: MYSQLHOST
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: MYSQLHOST
        - name: MYSQLPORT
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: MYSQLPORT
        - name: CARTDATABASE
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: CARTDATABASE
        - name: ITEM_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: ITEM_SERVICE_URL
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: USER_SERVICE_URL
---
kind: Service
apiVersion: v1
metadata:
  name: ms-asr-store-cart-service
  labels:
    app: ms-asr-store
spec:
  selector:
    app: ms-asr-store-cart
  type: NodePort
  ports:
  - name: cart-port
    port: 3003
    targetPort: 3003
    nodePort: 30003