apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-asr-store-client-deployment
  labels:
    app: ms-asr-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-asr-store-client
  template:
    metadata:
      labels:
        app: ms-asr-store-client
    spec:
      containers:
      - name: ms-asr-store-client
        image: client-service:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: VITE_USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-client-configmap
              key: VITE_USER_SERVICE_URL
        - name: VITE_ITEM_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-client-configmap
              key: VITE_ITEM_SERVICE_URL
        - name: VITE_CART_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-client-configmap
              key: VITE_CART_SERVICE_URL
        - name: VITE_ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-client-configmap
              key: VITE_ORDER_SERVICE_URL
        - name: VITE_ADMIN_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-client-configmap
              key: VITE_ADMIN_SERVICE_URL
---
kind: Service
apiVersion: v1
metadata:
  name: ms-asr-store-client-service
  labels:
    app: ms-asr-store
spec:
  selector:
    app: ms-asr-store-client
  type: NodePort
  ports:
  - name: client-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30006