apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-asr-store-configmap
  labels:
    app: ms-asr-store
data:
  NODE_ENV: production
  MYSQLHOST: "192.168.1.107" # ms-asr-store-db-service
  MYSQLPORT: "3306" # check in 'mysql-db.yaml'
  USER_SERVICE_PORT: "3001"
  ITEM_SERVICE_PORT: "3002"
  CART_SERVICE_PORT: "3003"
  ORDER_SERVICE_PORT: "3004"
  ADMIN_SERVICE_PORT: "3005"
  CLIENT_SERVICE_PORT: "3006"
  CARTDATABASE: cart_service
  USERDATABASE: user_service
  ITEMDATABASE: item_service
  ORDERDATABASE: order_service
  USER_SERVICE_URL: http://ms-asr-store-user-deployment/api/user
  ITEM_SERVICE_URL: http://ms-asr-store-item-deployment/api/items
  CART_SERVICE_URL: http://ms-asr-store-cart-deployment/api/cart
  ORDER_SERVICE_URL: http://ms-asr-store-order-deployment/api/order
  ADMIN_SERVICE_URL: http://ms-asr-store-admin-deployment/api/admin
  CLIENT_SERVICE_URL: http://ms-asr-store-client-deployment
  ZC_URL: https://test.zaincash.iq
  TRANSACTION_INIT_ROUTE: /transaction/init