apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-asr-store-item-deployment
  labels:
    app: ms-asr-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-asr-store-item
  template:
    metadata:
      labels:
        app: ms-asr-store-item
    spec:
      containers:
        - name: ms-asr-store-item
          image: item-service:v1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 20
          env:
            - name: MYSQLUSER
              valueFrom:
                secretKeyRef:
                  name: ms-asr-store-secert
                  key: MYSQLUSER
            - name: MYSQLPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-asr-store-secert
                  key: MYSQLPASSWORD
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ms-asr-store-configmap
                  key: NODE_ENV
            - name: ITEM_SERVICE_PORT
              value: "3002"
            - name: MYSQLHOST
              valueFrom:
                configMapKeyRef:
                  name: ms-asr-store-configmap
                  key: MYSQLHOST
            - name: MYSQLPORT
              valueFrom:
                configMapKeyRef:
                  name: ms-asr-store-configmap
                  key: MYSQLPORT
            - name: ITEMDATABASE
              valueFrom:
                configMapKeyRef:
                  name: ms-asr-store-configmap
                  key: ITEMDATABASE      
---
kind: Service
apiVersion: v1
metadata:
  name: ms-asr-store-item-service
  labels:
    app: ms-asr-store
spec:
  selector:
    app: ms-asr-store-item
  type: NodePort
  ports:
  - name: item-port
    port: 3002
    targetPort: 3002
    nodePort: 30002