apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-asr-store-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: C:/ProgramData/MySQL/MySQL Server 8.0/Data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-asr-store-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---

apiVersion: v1
kind: Deployment
metadata:
  name: ms-asr-store-db-deployment
  labels:
    app: ms-asr-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-asr-store-db
  template:
    metadata:
      labels:
        app: ms-asr-store
    spec:
      containers:
      - name: ms-asr-store-db
        image: mysql:8.3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQLUSER
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLUSER
        - name: MYSQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLPASSWORD
        - name: MYSQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLPASSWORD
        volumeMounts:
            - name: ms-asr-store-db-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: ms-asr-store-db-volume
          persistentVolumeClaim:
            claimName: ms-asr-store-db-pv

---

kind: Service
apiVersion: v1
metadata:
  name: ms-asr-store-db-service
  labels:
    app: ms-asr-store
spec:
  selector:
    app: ms-asr-store-db
  type: ClusterIP
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
  