apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-asr-store-user-deployment
  labels:
    app: ms-asr-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-asr-store-user
  template:
    metadata:
      labels:
        app: ms-asr-store-user
    spec:
      containers:
      - name: ms-asr-store-user
        image: user-service:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: MYSQLUSER
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLUSER
        - name: MYSQLPASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: MYSQLPASSWORD
        - name: LOGIN_JWT_SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: LOGIN_JWT_SESSION_SECRET
        - name: FACEBOOK_APP_ID
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: FACEBOOK_APP_ID
        - name: FACEBOOK_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: FACEBOOK_APP_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ms-asr-store-secert
              key: GOOGLE_CLIENT_SECRET
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: NODE_ENV
        - name: USER_SERVICE_PORT
          value: "3001"
        - name: MYSQLHOST
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: MYSQLHOST
        - name: MYSQLPORT
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: MYSQLPORT
        - name: USERDATABASE
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: USERDATABASE
        - name: CART_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ms-asr-store-configmap
              key: CART_SERVICE_URL
---
kind: Service
apiVersion: v1
metadata:
  name: ms-asr-store-user-service
  labels:
    app: ms-asr-store
spec:
  selector:
    app: ms-asr-store-user
  type: NodePort
  ports:
  - name: user-port
    port: 3001
    targetPort: 3001
    nodePort: 30001